### ISSUE TITLE
NMEA 2000 non-isolated input and output and ground loops

### ISSUE THREAD

**Issue by mgrouch** [OpenMarine/MacArthur-HAT#14]
NMEA 2000 on this hat has non-isolated input and output. Will it create issues with 
ground loops?

thanks

**Comment by sailoog** [comment]
https://macarthur-hat-documentation.readthedocs.io/en/latest/nmea2000.html

**Comment by mgrouch** [comment]
What can happen if someone plugs in pi from shore power and NMEA 2000 network is powered from a battery?

thanks

**Comment by sailoog** [comment]
And that is why manuals and instructions exist.
