### ISSUE TITLE
CAN hangs on pi 4 after last raspi upgrades.

### ISSUE THREAD

**Issue by hwater** [OpenMarine/MacArthur-HAT#15]
if the can line is uncommented in config.txt the pi runs again - of course without canbus.

regards - holger

**Comment by hwater** [comment]
if the can line is uncommented in config.txt the pi runs again - of course without canbus.

**Comment by sailoog** [comment]
closed by https://forum.openmarine.net/showthread.php?tid=5740&pid=31811#pid31811
